//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IA_06.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://books/", ConfigurationName="ServiceReference1.BookManager")]
    public interface BookManager {
        
        // CODEGEN: Parametr „book” wymaga dodatkowych informacji o schemacie, których nie można uzyskać w trybie parametru. Określony atrybut to „System.Xml.Serialization.XmlElementAttribute”.
        [System.ServiceModel.OperationContractAttribute(Action="http://books/BookManager/addRequest", ReplyAction="http://books/BookManager/addResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IA_06.ServiceReference1.addResponse add(IA_06.ServiceReference1.addRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://books/BookManager/addRequest", ReplyAction="http://books/BookManager/addResponse")]
        System.Threading.Tasks.Task<IA_06.ServiceReference1.addResponse> addAsync(IA_06.ServiceReference1.addRequest request);
        
        // CODEGEN: Parametr „book” wymaga dodatkowych informacji o schemacie, których nie można uzyskać w trybie parametru. Określony atrybut to „System.Xml.Serialization.XmlElementAttribute”.
        [System.ServiceModel.OperationContractAttribute(Action="http://books/BookManager/searchByTitleRequest", ReplyAction="http://books/BookManager/searchByTitleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="book")]
        IA_06.ServiceReference1.searchByTitleResponse searchByTitle(IA_06.ServiceReference1.searchByTitleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://books/BookManager/searchByTitleRequest", ReplyAction="http://books/BookManager/searchByTitleResponse")]
        System.Threading.Tasks.Task<IA_06.ServiceReference1.searchByTitleResponse> searchByTitleAsync(IA_06.ServiceReference1.searchByTitleRequest request);
        
        // CODEGEN: Parametr „book” wymaga dodatkowych informacji o schemacie, których nie można uzyskać w trybie parametru. Określony atrybut to „System.Xml.Serialization.XmlElementAttribute”.
        [System.ServiceModel.OperationContractAttribute(Action="http://books/BookManager/searchByAuthorRequest", ReplyAction="http://books/BookManager/searchByAuthorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="book")]
        IA_06.ServiceReference1.searchByAuthorResponse searchByAuthor(IA_06.ServiceReference1.searchByAuthorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://books/BookManager/searchByAuthorRequest", ReplyAction="http://books/BookManager/searchByAuthorResponse")]
        System.Threading.Tasks.Task<IA_06.ServiceReference1.searchByAuthorResponse> searchByAuthorAsync(IA_06.ServiceReference1.searchByAuthorRequest request);
        
        // CODEGEN: Parametr „book” wymaga dodatkowych informacji o schemacie, których nie można uzyskać w trybie parametru. Określony atrybut to „System.Xml.Serialization.XmlElementAttribute”.
        [System.ServiceModel.OperationContractAttribute(Action="http://books/BookManager/searchByISBNRequest", ReplyAction="http://books/BookManager/searchByISBNResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="book")]
        IA_06.ServiceReference1.searchByISBNResponse searchByISBN(IA_06.ServiceReference1.searchByISBNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://books/BookManager/searchByISBNRequest", ReplyAction="http://books/BookManager/searchByISBNResponse")]
        System.Threading.Tasks.Task<IA_06.ServiceReference1.searchByISBNResponse> searchByISBNAsync(IA_06.ServiceReference1.searchByISBNRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://books/")]
    public partial class book : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string authorField;
        
        private string isbnField;
        
        private int pagesField;
        
        private string publisherField;
        
        private string titleField;
        
        private int yearField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
                this.RaisePropertyChanged("author");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string isbn {
            get {
                return this.isbnField;
            }
            set {
                this.isbnField = value;
                this.RaisePropertyChanged("isbn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int pages {
            get {
                return this.pagesField;
            }
            set {
                this.pagesField = value;
                this.RaisePropertyChanged("pages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string publisher {
            get {
                return this.publisherField;
            }
            set {
                this.publisherField = value;
                this.RaisePropertyChanged("publisher");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="add", WrapperNamespace="http://books/", IsWrapped=true)]
    public partial class addRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://books/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IA_06.ServiceReference1.book book;
        
        public addRequest() {
        }
        
        public addRequest(IA_06.ServiceReference1.book book) {
            this.book = book;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addResponse", WrapperNamespace="http://books/", IsWrapped=true)]
    public partial class addResponse {
        
        public addResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchByTitle", WrapperNamespace="http://books/", IsWrapped=true)]
    public partial class searchByTitleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://books/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string title;
        
        public searchByTitleRequest() {
        }
        
        public searchByTitleRequest(string title) {
            this.title = title;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchByTitleResponse", WrapperNamespace="http://books/", IsWrapped=true)]
    public partial class searchByTitleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://books/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("book", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IA_06.ServiceReference1.book[] book;
        
        public searchByTitleResponse() {
        }
        
        public searchByTitleResponse(IA_06.ServiceReference1.book[] book) {
            this.book = book;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchByAuthor", WrapperNamespace="http://books/", IsWrapped=true)]
    public partial class searchByAuthorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://books/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string author;
        
        public searchByAuthorRequest() {
        }
        
        public searchByAuthorRequest(string author) {
            this.author = author;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchByAuthorResponse", WrapperNamespace="http://books/", IsWrapped=true)]
    public partial class searchByAuthorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://books/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("book", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IA_06.ServiceReference1.book[] book;
        
        public searchByAuthorResponse() {
        }
        
        public searchByAuthorResponse(IA_06.ServiceReference1.book[] book) {
            this.book = book;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchByISBN", WrapperNamespace="http://books/", IsWrapped=true)]
    public partial class searchByISBNRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://books/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string isbn;
        
        public searchByISBNRequest() {
        }
        
        public searchByISBNRequest(string isbn) {
            this.isbn = isbn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchByISBNResponse", WrapperNamespace="http://books/", IsWrapped=true)]
    public partial class searchByISBNResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://books/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IA_06.ServiceReference1.book book;
        
        public searchByISBNResponse() {
        }
        
        public searchByISBNResponse(IA_06.ServiceReference1.book book) {
            this.book = book;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BookManagerChannel : IA_06.ServiceReference1.BookManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookManagerClient : System.ServiceModel.ClientBase<IA_06.ServiceReference1.BookManager>, IA_06.ServiceReference1.BookManager {
        
        public BookManagerClient() {
        }
        
        public BookManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IA_06.ServiceReference1.addResponse IA_06.ServiceReference1.BookManager.add(IA_06.ServiceReference1.addRequest request) {
            return base.Channel.add(request);
        }
        
        public void add(IA_06.ServiceReference1.book book) {
            IA_06.ServiceReference1.addRequest inValue = new IA_06.ServiceReference1.addRequest();
            inValue.book = book;
            IA_06.ServiceReference1.addResponse retVal = ((IA_06.ServiceReference1.BookManager)(this)).add(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IA_06.ServiceReference1.addResponse> IA_06.ServiceReference1.BookManager.addAsync(IA_06.ServiceReference1.addRequest request) {
            return base.Channel.addAsync(request);
        }
        
        public System.Threading.Tasks.Task<IA_06.ServiceReference1.addResponse> addAsync(IA_06.ServiceReference1.book book) {
            IA_06.ServiceReference1.addRequest inValue = new IA_06.ServiceReference1.addRequest();
            inValue.book = book;
            return ((IA_06.ServiceReference1.BookManager)(this)).addAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IA_06.ServiceReference1.searchByTitleResponse IA_06.ServiceReference1.BookManager.searchByTitle(IA_06.ServiceReference1.searchByTitleRequest request) {
            return base.Channel.searchByTitle(request);
        }
        
        public IA_06.ServiceReference1.book[] searchByTitle(string title) {
            IA_06.ServiceReference1.searchByTitleRequest inValue = new IA_06.ServiceReference1.searchByTitleRequest();
            inValue.title = title;
            IA_06.ServiceReference1.searchByTitleResponse retVal = ((IA_06.ServiceReference1.BookManager)(this)).searchByTitle(inValue);
            return retVal.book;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IA_06.ServiceReference1.searchByTitleResponse> IA_06.ServiceReference1.BookManager.searchByTitleAsync(IA_06.ServiceReference1.searchByTitleRequest request) {
            return base.Channel.searchByTitleAsync(request);
        }
        
        public System.Threading.Tasks.Task<IA_06.ServiceReference1.searchByTitleResponse> searchByTitleAsync(string title) {
            IA_06.ServiceReference1.searchByTitleRequest inValue = new IA_06.ServiceReference1.searchByTitleRequest();
            inValue.title = title;
            return ((IA_06.ServiceReference1.BookManager)(this)).searchByTitleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IA_06.ServiceReference1.searchByAuthorResponse IA_06.ServiceReference1.BookManager.searchByAuthor(IA_06.ServiceReference1.searchByAuthorRequest request) {
            return base.Channel.searchByAuthor(request);
        }
        
        public IA_06.ServiceReference1.book[] searchByAuthor(string author) {
            IA_06.ServiceReference1.searchByAuthorRequest inValue = new IA_06.ServiceReference1.searchByAuthorRequest();
            inValue.author = author;
            IA_06.ServiceReference1.searchByAuthorResponse retVal = ((IA_06.ServiceReference1.BookManager)(this)).searchByAuthor(inValue);
            return retVal.book;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IA_06.ServiceReference1.searchByAuthorResponse> IA_06.ServiceReference1.BookManager.searchByAuthorAsync(IA_06.ServiceReference1.searchByAuthorRequest request) {
            return base.Channel.searchByAuthorAsync(request);
        }
        
        public System.Threading.Tasks.Task<IA_06.ServiceReference1.searchByAuthorResponse> searchByAuthorAsync(string author) {
            IA_06.ServiceReference1.searchByAuthorRequest inValue = new IA_06.ServiceReference1.searchByAuthorRequest();
            inValue.author = author;
            return ((IA_06.ServiceReference1.BookManager)(this)).searchByAuthorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IA_06.ServiceReference1.searchByISBNResponse IA_06.ServiceReference1.BookManager.searchByISBN(IA_06.ServiceReference1.searchByISBNRequest request) {
            return base.Channel.searchByISBN(request);
        }
        
        public IA_06.ServiceReference1.book searchByISBN(string isbn) {
            IA_06.ServiceReference1.searchByISBNRequest inValue = new IA_06.ServiceReference1.searchByISBNRequest();
            inValue.isbn = isbn;
            IA_06.ServiceReference1.searchByISBNResponse retVal = ((IA_06.ServiceReference1.BookManager)(this)).searchByISBN(inValue);
            return retVal.book;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IA_06.ServiceReference1.searchByISBNResponse> IA_06.ServiceReference1.BookManager.searchByISBNAsync(IA_06.ServiceReference1.searchByISBNRequest request) {
            return base.Channel.searchByISBNAsync(request);
        }
        
        public System.Threading.Tasks.Task<IA_06.ServiceReference1.searchByISBNResponse> searchByISBNAsync(string isbn) {
            IA_06.ServiceReference1.searchByISBNRequest inValue = new IA_06.ServiceReference1.searchByISBNRequest();
            inValue.isbn = isbn;
            return ((IA_06.ServiceReference1.BookManager)(this)).searchByISBNAsync(inValue);
        }
    }
}
