//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IA_06.Spells {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://spell/", ConfigurationName="Spells.SpellManager")]
    public interface SpellManager {
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://spell/SpellManager/addRequest", ReplyAction="http://spell/SpellManager/addResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CharacterClass[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Subclass[]))]
        IA_06.Spells.addResponse add(IA_06.Spells.addRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://spell/SpellManager/addRequest", ReplyAction="http://spell/SpellManager/addResponse")]
        System.Threading.Tasks.Task<IA_06.Spells.addResponse> addAsync(IA_06.Spells.addRequest request);
        
        // CODEGEN: Parameter 'spell' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://spell/SpellManager/searchByNameRequest", ReplyAction="http://spell/SpellManager/searchByNameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CharacterClass[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Subclass[]))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="spell")]
        IA_06.Spells.searchByNameResponse searchByName(IA_06.Spells.searchByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://spell/SpellManager/searchByNameRequest", ReplyAction="http://spell/SpellManager/searchByNameResponse")]
        System.Threading.Tasks.Task<IA_06.Spells.searchByNameResponse> searchByNameAsync(IA_06.Spells.searchByNameRequest request);
        
        // CODEGEN: Parameter 'spell' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://spell/SpellManager/searchByClassRequest", ReplyAction="http://spell/SpellManager/searchByClassResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CharacterClass[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Subclass[]))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="spell")]
        IA_06.Spells.searchByClassResponse searchByClass(IA_06.Spells.searchByClassRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://spell/SpellManager/searchByClassRequest", ReplyAction="http://spell/SpellManager/searchByClassResponse")]
        System.Threading.Tasks.Task<IA_06.Spells.searchByClassResponse> searchByClassAsync(IA_06.Spells.searchByClassRequest request);
        
        // CODEGEN: Parameter 'spell' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://spell/SpellManager/searchBySchoolRequest", ReplyAction="http://spell/SpellManager/searchBySchoolResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CharacterClass[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Subclass[]))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="spell")]
        IA_06.Spells.searchBySchoolResponse searchBySchool(IA_06.Spells.searchBySchoolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://spell/SpellManager/searchBySchoolRequest", ReplyAction="http://spell/SpellManager/searchBySchoolResponse")]
        System.Threading.Tasks.Task<IA_06.Spells.searchBySchoolResponse> searchBySchoolAsync(IA_06.Spells.searchBySchoolRequest request);
        
        // CODEGEN: Parameter 'spell' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://spell/SpellManager/searchByLevelRequest", ReplyAction="http://spell/SpellManager/searchByLevelResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CharacterClass[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Subclass[]))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="spell")]
        IA_06.Spells.searchByLevelResponse searchByLevel(IA_06.Spells.searchByLevelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://spell/SpellManager/searchByLevelRequest", ReplyAction="http://spell/SpellManager/searchByLevelResponse")]
        System.Threading.Tasks.Task<IA_06.Spells.searchByLevelResponse> searchByLevelAsync(IA_06.Spells.searchByLevelRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://spell/SpellManager/add2Request", ReplyAction="http://spell/SpellManager/add2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CharacterClass[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Subclass[]))]
        IA_06.Spells.add2Response add2(IA_06.Spells.add2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://spell/SpellManager/add2Request", ReplyAction="http://spell/SpellManager/add2Response")]
        System.Threading.Tasks.Task<IA_06.Spells.add2Response> add2Async(IA_06.Spells.add2Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://spell/")]
    public partial class school : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://spell/")]
    public partial class Spell : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string casting_timeField;
        
        private CharacterClass[] characterClassesField;
        
        private string[] componentsField;
        
        private string concentrationField;
        
        private string[] descField;
        
        private string durationField;
        
        private string[] higher_levelField;
        
        private string idField;
        
        private int indexField;
        
        private int levelField;
        
        private string materialField;
        
        private string nameField;
        
        private string pageField;
        
        private string rangeField;
        
        private string ritualField;
        
        private school schoolField;
        
        private Subclass[] subclassesField;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string casting_time {
            get {
                return this.casting_timeField;
            }
            set {
                this.casting_timeField = value;
                this.RaisePropertyChanged("casting_time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CharacterClass[] characterClasses {
            get {
                return this.characterClassesField;
            }
            set {
                this.characterClassesField = value;
                this.RaisePropertyChanged("characterClasses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] components {
            get {
                return this.componentsField;
            }
            set {
                this.componentsField = value;
                this.RaisePropertyChanged("components");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string concentration {
            get {
                return this.concentrationField;
            }
            set {
                this.concentrationField = value;
                this.RaisePropertyChanged("concentration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
                this.RaisePropertyChanged("duration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] higher_level {
            get {
                return this.higher_levelField;
            }
            set {
                this.higher_levelField = value;
                this.RaisePropertyChanged("higher_level");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
                this.RaisePropertyChanged("index");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
                this.RaisePropertyChanged("level");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string material {
            get {
                return this.materialField;
            }
            set {
                this.materialField = value;
                this.RaisePropertyChanged("material");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string page {
            get {
                return this.pageField;
            }
            set {
                this.pageField = value;
                this.RaisePropertyChanged("page");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string range {
            get {
                return this.rangeField;
            }
            set {
                this.rangeField = value;
                this.RaisePropertyChanged("range");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string ritual {
            get {
                return this.ritualField;
            }
            set {
                this.ritualField = value;
                this.RaisePropertyChanged("ritual");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public school school {
            get {
                return this.schoolField;
            }
            set {
                this.schoolField = value;
                this.RaisePropertyChanged("school");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Subclass[] subclasses {
            get {
                return this.subclassesField;
            }
            set {
                this.subclassesField = value;
                this.RaisePropertyChanged("subclasses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://spell/")]
    public partial class CharacterClass : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://spell/")]
    public partial class Subclass : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="add", WrapperNamespace="http://spell/", IsWrapped=true)]
    public partial class addRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spell/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spell/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spell/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spell/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("arg3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spell/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("arg4", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] arg4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spell/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spell/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg6;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spell/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute("arg7", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] arg7;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spell/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg8;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spell/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg9;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spell/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg10;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spell/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg11;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spell/", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg12;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spell/", Order=13)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg13;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spell/", Order=14)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IA_06.Spells.school arg14;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spell/", Order=15)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IA_06.Spells.CharacterClass arg15;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spell/", Order=16)]
        [System.Xml.Serialization.XmlElementAttribute("arg16", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IA_06.Spells.Subclass[] arg16;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spell/", Order=17)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg17;
        
        public addRequest() {
        }
        
        public addRequest(
                    string arg0, 
                    int arg1, 
                    string arg2, 
                    string[] arg3, 
                    string[] arg4, 
                    string arg5, 
                    string arg6, 
                    string[] arg7, 
                    string arg8, 
                    string arg9, 
                    string arg10, 
                    string arg11, 
                    string arg12, 
                    int arg13, 
                    IA_06.Spells.school arg14, 
                    IA_06.Spells.CharacterClass arg15, 
                    IA_06.Spells.Subclass[] arg16, 
                    string arg17) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
            this.arg7 = arg7;
            this.arg8 = arg8;
            this.arg9 = arg9;
            this.arg10 = arg10;
            this.arg11 = arg11;
            this.arg12 = arg12;
            this.arg13 = arg13;
            this.arg14 = arg14;
            this.arg15 = arg15;
            this.arg16 = arg16;
            this.arg17 = arg17;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addResponse", WrapperNamespace="http://spell/", IsWrapped=true)]
    public partial class addResponse {
        
        public addResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchByName", WrapperNamespace="http://spell/", IsWrapped=true)]
    public partial class searchByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spell/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public searchByNameRequest() {
        }
        
        public searchByNameRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchByNameResponse", WrapperNamespace="http://spell/", IsWrapped=true)]
    public partial class searchByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spell/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("spell", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IA_06.Spells.Spell[] spell;
        
        public searchByNameResponse() {
        }
        
        public searchByNameResponse(IA_06.Spells.Spell[] spell) {
            this.spell = spell;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchByClass", WrapperNamespace="http://spell/", IsWrapped=true)]
    public partial class searchByClassRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spell/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string className;
        
        public searchByClassRequest() {
        }
        
        public searchByClassRequest(string className) {
            this.className = className;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchByClassResponse", WrapperNamespace="http://spell/", IsWrapped=true)]
    public partial class searchByClassResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spell/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("spell", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IA_06.Spells.Spell[] spell;
        
        public searchByClassResponse() {
        }
        
        public searchByClassResponse(IA_06.Spells.Spell[] spell) {
            this.spell = spell;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchBySchool", WrapperNamespace="http://spell/", IsWrapped=true)]
    public partial class searchBySchoolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spell/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string school;
        
        public searchBySchoolRequest() {
        }
        
        public searchBySchoolRequest(string school) {
            this.school = school;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchBySchoolResponse", WrapperNamespace="http://spell/", IsWrapped=true)]
    public partial class searchBySchoolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spell/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("spell", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IA_06.Spells.Spell[] spell;
        
        public searchBySchoolResponse() {
        }
        
        public searchBySchoolResponse(IA_06.Spells.Spell[] spell) {
            this.spell = spell;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchByLevel", WrapperNamespace="http://spell/", IsWrapped=true)]
    public partial class searchByLevelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spell/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int level;
        
        public searchByLevelRequest() {
        }
        
        public searchByLevelRequest(int level) {
            this.level = level;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchByLevelResponse", WrapperNamespace="http://spell/", IsWrapped=true)]
    public partial class searchByLevelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spell/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("spell", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IA_06.Spells.Spell[] spell;
        
        public searchByLevelResponse() {
        }
        
        public searchByLevelResponse(IA_06.Spells.Spell[] spell) {
            this.spell = spell;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="add2", WrapperNamespace="http://spell/", IsWrapped=true)]
    public partial class add2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spell/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IA_06.Spells.Spell arg0;
        
        public add2Request() {
        }
        
        public add2Request(IA_06.Spells.Spell arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="add2Response", WrapperNamespace="http://spell/", IsWrapped=true)]
    public partial class add2Response {
        
        public add2Response() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SpellManagerChannel : IA_06.Spells.SpellManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SpellManagerClient : System.ServiceModel.ClientBase<IA_06.Spells.SpellManager>, IA_06.Spells.SpellManager {
        
        public SpellManagerClient() {
        }
        
        public SpellManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SpellManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpellManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpellManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IA_06.Spells.addResponse IA_06.Spells.SpellManager.add(IA_06.Spells.addRequest request) {
            return base.Channel.add(request);
        }
        
        public void add(
                    string arg0, 
                    int arg1, 
                    string arg2, 
                    string[] arg3, 
                    string[] arg4, 
                    string arg5, 
                    string arg6, 
                    string[] arg7, 
                    string arg8, 
                    string arg9, 
                    string arg10, 
                    string arg11, 
                    string arg12, 
                    int arg13, 
                    IA_06.Spells.school arg14, 
                    IA_06.Spells.CharacterClass arg15, 
                    IA_06.Spells.Subclass[] arg16, 
                    string arg17) {
            IA_06.Spells.addRequest inValue = new IA_06.Spells.addRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            inValue.arg6 = arg6;
            inValue.arg7 = arg7;
            inValue.arg8 = arg8;
            inValue.arg9 = arg9;
            inValue.arg10 = arg10;
            inValue.arg11 = arg11;
            inValue.arg12 = arg12;
            inValue.arg13 = arg13;
            inValue.arg14 = arg14;
            inValue.arg15 = arg15;
            inValue.arg16 = arg16;
            inValue.arg17 = arg17;
            IA_06.Spells.addResponse retVal = ((IA_06.Spells.SpellManager)(this)).add(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IA_06.Spells.addResponse> IA_06.Spells.SpellManager.addAsync(IA_06.Spells.addRequest request) {
            return base.Channel.addAsync(request);
        }
        
        public System.Threading.Tasks.Task<IA_06.Spells.addResponse> addAsync(
                    string arg0, 
                    int arg1, 
                    string arg2, 
                    string[] arg3, 
                    string[] arg4, 
                    string arg5, 
                    string arg6, 
                    string[] arg7, 
                    string arg8, 
                    string arg9, 
                    string arg10, 
                    string arg11, 
                    string arg12, 
                    int arg13, 
                    IA_06.Spells.school arg14, 
                    IA_06.Spells.CharacterClass arg15, 
                    IA_06.Spells.Subclass[] arg16, 
                    string arg17) {
            IA_06.Spells.addRequest inValue = new IA_06.Spells.addRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            inValue.arg6 = arg6;
            inValue.arg7 = arg7;
            inValue.arg8 = arg8;
            inValue.arg9 = arg9;
            inValue.arg10 = arg10;
            inValue.arg11 = arg11;
            inValue.arg12 = arg12;
            inValue.arg13 = arg13;
            inValue.arg14 = arg14;
            inValue.arg15 = arg15;
            inValue.arg16 = arg16;
            inValue.arg17 = arg17;
            return ((IA_06.Spells.SpellManager)(this)).addAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IA_06.Spells.searchByNameResponse IA_06.Spells.SpellManager.searchByName(IA_06.Spells.searchByNameRequest request) {
            return base.Channel.searchByName(request);
        }
        
        public IA_06.Spells.Spell[] searchByName(string name) {
            IA_06.Spells.searchByNameRequest inValue = new IA_06.Spells.searchByNameRequest();
            inValue.name = name;
            IA_06.Spells.searchByNameResponse retVal = ((IA_06.Spells.SpellManager)(this)).searchByName(inValue);
            return retVal.spell;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IA_06.Spells.searchByNameResponse> IA_06.Spells.SpellManager.searchByNameAsync(IA_06.Spells.searchByNameRequest request) {
            return base.Channel.searchByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<IA_06.Spells.searchByNameResponse> searchByNameAsync(string name) {
            IA_06.Spells.searchByNameRequest inValue = new IA_06.Spells.searchByNameRequest();
            inValue.name = name;
            return ((IA_06.Spells.SpellManager)(this)).searchByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IA_06.Spells.searchByClassResponse IA_06.Spells.SpellManager.searchByClass(IA_06.Spells.searchByClassRequest request) {
            return base.Channel.searchByClass(request);
        }
        
        public IA_06.Spells.Spell[] searchByClass(string className) {
            IA_06.Spells.searchByClassRequest inValue = new IA_06.Spells.searchByClassRequest();
            inValue.className = className;
            IA_06.Spells.searchByClassResponse retVal = ((IA_06.Spells.SpellManager)(this)).searchByClass(inValue);
            return retVal.spell;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IA_06.Spells.searchByClassResponse> IA_06.Spells.SpellManager.searchByClassAsync(IA_06.Spells.searchByClassRequest request) {
            return base.Channel.searchByClassAsync(request);
        }
        
        public System.Threading.Tasks.Task<IA_06.Spells.searchByClassResponse> searchByClassAsync(string className) {
            IA_06.Spells.searchByClassRequest inValue = new IA_06.Spells.searchByClassRequest();
            inValue.className = className;
            return ((IA_06.Spells.SpellManager)(this)).searchByClassAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IA_06.Spells.searchBySchoolResponse IA_06.Spells.SpellManager.searchBySchool(IA_06.Spells.searchBySchoolRequest request) {
            return base.Channel.searchBySchool(request);
        }
        
        public IA_06.Spells.Spell[] searchBySchool(string school) {
            IA_06.Spells.searchBySchoolRequest inValue = new IA_06.Spells.searchBySchoolRequest();
            inValue.school = school;
            IA_06.Spells.searchBySchoolResponse retVal = ((IA_06.Spells.SpellManager)(this)).searchBySchool(inValue);
            return retVal.spell;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IA_06.Spells.searchBySchoolResponse> IA_06.Spells.SpellManager.searchBySchoolAsync(IA_06.Spells.searchBySchoolRequest request) {
            return base.Channel.searchBySchoolAsync(request);
        }
        
        public System.Threading.Tasks.Task<IA_06.Spells.searchBySchoolResponse> searchBySchoolAsync(string school) {
            IA_06.Spells.searchBySchoolRequest inValue = new IA_06.Spells.searchBySchoolRequest();
            inValue.school = school;
            return ((IA_06.Spells.SpellManager)(this)).searchBySchoolAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IA_06.Spells.searchByLevelResponse IA_06.Spells.SpellManager.searchByLevel(IA_06.Spells.searchByLevelRequest request) {
            return base.Channel.searchByLevel(request);
        }
        
        public IA_06.Spells.Spell[] searchByLevel(int level) {
            IA_06.Spells.searchByLevelRequest inValue = new IA_06.Spells.searchByLevelRequest();
            inValue.level = level;
            IA_06.Spells.searchByLevelResponse retVal = ((IA_06.Spells.SpellManager)(this)).searchByLevel(inValue);
            return retVal.spell;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IA_06.Spells.searchByLevelResponse> IA_06.Spells.SpellManager.searchByLevelAsync(IA_06.Spells.searchByLevelRequest request) {
            return base.Channel.searchByLevelAsync(request);
        }
        
        public System.Threading.Tasks.Task<IA_06.Spells.searchByLevelResponse> searchByLevelAsync(int level) {
            IA_06.Spells.searchByLevelRequest inValue = new IA_06.Spells.searchByLevelRequest();
            inValue.level = level;
            return ((IA_06.Spells.SpellManager)(this)).searchByLevelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IA_06.Spells.add2Response IA_06.Spells.SpellManager.add2(IA_06.Spells.add2Request request) {
            return base.Channel.add2(request);
        }
        
        public void add2(IA_06.Spells.Spell arg0) {
            IA_06.Spells.add2Request inValue = new IA_06.Spells.add2Request();
            inValue.arg0 = arg0;
            IA_06.Spells.add2Response retVal = ((IA_06.Spells.SpellManager)(this)).add2(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IA_06.Spells.add2Response> IA_06.Spells.SpellManager.add2Async(IA_06.Spells.add2Request request) {
            return base.Channel.add2Async(request);
        }
        
        public System.Threading.Tasks.Task<IA_06.Spells.add2Response> add2Async(IA_06.Spells.Spell arg0) {
            IA_06.Spells.add2Request inValue = new IA_06.Spells.add2Request();
            inValue.arg0 = arg0;
            return ((IA_06.Spells.SpellManager)(this)).add2Async(inValue);
        }
    }
}
